export const animeEffects = [
  "rotate",
  "rotate-inv",
  "wiggle",
  "parrot",
  "zoom",
  "inversion",
  "turn",
  "turn-v",
  "happa",
  "pyon",
  "flashy",
  "pull",
  "atsumori",
  "stretch",
  "stretch-v",
  "conga",
  "conga-inv",
  "marquee",
  "marquee-inv",
  "rainbow",
  "ascension",
  "shake",
  "party",
  "attract",
];
export const sizeEffects = ["ex-large", "large", "small"];
