[package]
name = "markdown-trap-syntax"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
markdown-parser = { git = "https://github.com/traq-markdown-parser/core.git", rev = "fd5c12c919719ba771c62d12585f667d106bfc8d", version = "0.1.0" }
markdown-commonmark = { git = "https://github.com/traq-markdown-parser/commonmark.git", rev = "9758568592c8fc1b13e56e101e31308a55affdb4", version = "0.1.0" }
markdown-trap-contracts = { path = "../contracts" }
markdown-definitions = { git = "https://github.com/traq-markdown-parser/core.git", rev = "fd5c12c919719ba771c62d12585f667d106bfc8d", version = "0.1.0" }
serde_json = { version = "1", features = ["arbitrary_precision"] }
regex = "1"
