name: Rust CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo test --locked --workspace --all-features
      - run: cargo fmt --all --check
      - run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings
