name: Rust and TypeScript CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    defaults:
      run:
        working-directory: trap-extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: trap-extension
      - uses: actions/checkout@v6
        with:
          repository: traq-markdown-parser/core
          path: core
      - uses: actions/checkout@v6
        with:
          repository: traq-markdown-parser/commonmark
          path: commonmark
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: cargo test --locked --workspace --all-features
      - run: cargo fmt --all --check
      - run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

      - run: npm ci && npm run build
        working-directory: core
      - run: npm ci && npm run build
        working-directory: commonmark
      - run: npm ci
      - run: npm run generate:bindings
      - run: git diff --exit-code -- typescript/generated
      - run: npm run build
      - run: npm run typecheck
